### ISSUE TITLE
AVIF support

### ISSUE THREAD

**Issue by multipliedtwice** [unjs/image-meta#2]
Hello, do you plan to enable support of AVIF files?

**Comment by pi0** [comment]
Sorry for checking late on this. PR more than welcome!

**Comment by pi0** [comment]
Potentially helpful: https://github.com/sindresorhus/file-type/blob/ca7a03c26761444e024764a38d16597455281cfd/core.js#L517

**Comment by Vahagn-Zaqaryan** [comment]
Hey Unjs team, I'd like to know if there are any updates on this feature? 

Currently, I'm using @nuxt/image, which relies on the IPX library. In turn, IPX uses image-mate for detecting the type and size of images. I use AVIF images sourced from a CMS, and I've encountered issues with those image's not processing at all and chasing midway.

By the way, I'm relatively new to the Unjs framework, but I love the philosophy behind it.

**Comment by pi0** [comment]
Supported in latest release thanks to @tasiotas!
